import Head from "next/head";
import Nav from "components/Nav";
import Hero from "components/Hero";
import Partners from "components/Partners";
import Info from "components/Info";
import Benefits from "components/Benefits";
import Plans from "components/Plans";
import Offers from "components/Offers";
import FAQs from "components/FAQs";
import DeviceSupport from "components/DeviceSupport";
import Footer from "components/Footer";
import { VStack } from "@chakra-ui/react";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <Hero />
      <VStack as={"main"} pos={"relative"} top={-16} spacing={16}>
        <Partners />
        <Info />
        <Benefits />
        <Plans />

        <Offers />
        <DeviceSupport />
        <FAQs />
      </VStack>
      <Footer />
      <style jsx global>{`
        html {
          scroll-behavior: smooth;
        }
      `}</style>
    </>
  );
}
